server:
  port: 8080
  servlet:
    context-path: /
    # session 过期时间，单位：秒
    session:
      timeout: 60
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 906913
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true


# 开启Mybatis下划线命名转驼峰命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true
